se corrige Dockerfile se corrige pipeline

diff --git a/.github/workflows/melichallenge_github_action_gradle.yaml b/.github/workflows/melichallenge_github_action_gradle.yaml
--- a/.github/workflows/melichallenge_github_action_gradle.yaml
+++ b/.github/workflows/melichallenge_github_action_gradle.yaml
@@ -24,13 +24,12 @@ jobs:
           java-version: 11
       - name: Grant execute permission for gradlew
         run: chmod +x gradlew
-      - name: Execute jacocoTestReport
-        run: ./gradlew test jacocoTestReport
+      - name: Build and Test with Gradle
+        run: ./gradlew build test --refresh-dependencies --no-daemon --continue
+      - name: Execute jacocoMergedReport
+        run: ./gradlew jacocoMergedReport
       - name: copy the reportTest to codeCoverage
-        run: cp build/reports/jacoco/report.xml jacoco.xml || echo "Code coverage failed"
-      - name: Build with Gradle
-        run: ./gradlew build --refresh-dependencies --no-daemon --continue
-# TODO: Add all other tasks that your project require in build job
+        run: cp build/reports/jacoco/jacocoMergedReport/jacocoMergedReport.xml jacoco.xml || echo "Code coverage failed"
   docker-build:
     runs-on: ubuntu-latest
     needs: build
@@ -51,4 +50,3 @@ jobs:
           java-version: 1.8
       - name: Grant execute permission for gradlew
         run: chmod +x gradlew
-# TODO: Add all other tasks that your project require in release job
